name: build-jamstack
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
    - run: |
      echo "hello ${{ github.event_name }} world."

