name: build-jamstack
on:
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - build
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello ${{ github.event_name }} world."
