name: build-jamstack
on:
  workflow_dispatch:
    inputs:
      description: 'Person to greet'
        required: false

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
    - run: |
      echo "hello ${{ github.event_name }} world."
